version: 1.0

mode: "DISTRIBUTED" # "SINGLE_THREAD", "MULTI_PROCESS", "DISTRIBUTED"
level: ERROR

formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  detailed:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(module)s - %(funcName)s - %(lineno)d - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  stream:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: detailed
    filename: dev_log.log
    mode: append
    maxBytes: 10485760 # 10MB
    backupCount: 5
